# Generated by Django 2.2.14 on 2022-04-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_auto_20190630_1408"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="stock",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.FloatField(default=1.1),
            preserve_default=False,
        ),
    ]
