# Generated by Django 2.2.14 on 2022-04-26 00:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_auto_20220426_0037"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="label",
        ),
    ]
