# Generated by Django 2.2.14 on 2022-04-26 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount_price',
        ),
    ]
