# Generated by Django 2.2.14 on 2022-04-26 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220426_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
