# Generated by Django 2.2.14 on 2022-04-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_order_cpf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="billing_address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="received",
        ),
        migrations.RemoveField(
            model_name="order",
            name="ref_code",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="price",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="priceSell",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
