# Generated by Django 2.2.14 on 2022-04-26 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_auto_20220426_1642"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="priceSell",
            new_name="sellPrice",
        ),
    ]
